const ALPHA_RESEARCH_FASTPLAY = [
	"R-Wpn-MG1Mk1", "R-Vehicle-Body01", "R-Sys-Spade1Mk1", "R-Vehicle-Prop-Wheels",
	"R-Sys-MobileRepairTurret01", "R-Sys-Engineering01", "R-Wpn-MG-Damage01",
	"R-Wpn-MG-ROF01", "R-Defense-Tower01", "R-Defense-TankTrap01", "R-Wpn-MG2Mk1",
	"R-Sys-Sensor-Turret01", "R-Struc-PowerModuleMk1", "R-Wpn-MG-Damage02",
	"R-Sys-Sensor-Tower01", "R-Defense-Tower02", "R-Wpn-MG3Mk1", "R-Defense-Tower03",
	"R-Wpn-MG-Damage03", "R-Wpn-Mortar01Lt", "R-Vehicle-Prop-Halftracks",
	"R-Wpn-Cannon1Mk1", "R-Wpn-Mortar-Damage01", "R-Wpn-Mortar-Damage02",
	"R-Wpn-Mortar-ROF01","R-Wpn-Cannon-Damage01", "R-Wpn-Cannon-Damage02",
	"R-Struc-Factory-Module", "R-Struc-Factory-Upgrade01",
	"R-Struc-Factory-Upgrade02", "R-Defense-HardcreteWall", "R-Struc-CommandRelay",
	"R-Comp-CommandTurret01", "R-Struc-RepairFacility", "R-Struc-RprFac-Upgrade01",
	"R-Struc-RprFac-Upgrade02", "R-Defense-MortarPit", "R-Defense-Pillbox01",
	"R-Defense-Pillbox04", "R-Defense-WallTower01", "R-Defense-WallTower02",
	"R-Defense-WallUpgrade01", "R-Defense-WallUpgrade02", "R-Defense-WallUpgrade03",
	"R-Struc-Materials01", "R-Struc-Materials02", "R-Struc-Materials03",
	"R-Wpn-Cannon2Mk1", "R-Defense-WallTower03", "R-Wpn-Rocket05-MiniPod",
	"R-Struc-Research-Module", "R-Vehicle-Engine01", "R-Defense-Tower06",
	"R-Defense-Pillbox06", "R-Wpn-Rocket-Damage01", "R-Wpn-Rocket-Damage02",
	"R-Wpn-Rocket-ROF01", "R-Wpn-Rocket-ROF02", "R-Wpn-Rocket-ROF03",
	"R-Defense-WallTower06", "R-Wpn-Rocket01-LtAT", "R-Wpn-Rocket03-HvAT",
	"R-Wpn-RocketSlow-Damage01", "R-Vehicle-Metals01", "R-Vehicle-Metals02",
	"R-Wpn-MG-Damage04", "R-Wpn-Rocket02-MRL", "R-Wpn-Rocket-Damage03",
	"R-Wpn-Mortar02Hvy", "R-Wpn-Mortar-Damage03", "R-Wpn-Cannon-Damage03",
	"R-Wpn-RocketSlow-Damage02", "R-Vehicle-Body11", "R-Defense-MRL",
	"R-Defense-HvyMor", "R-Struc-Research-Upgrade01", "R-Struc-Research-Upgrade02",
	"R-Struc-Research-Upgrade03", "R-Wpn-Mortar-Acc01", "R-Wpn-Rocket-Accuracy01",
	"R-Wpn-Rocket-Accuracy02", "R-Wpn-RocketSlow-Accuracy01", "R-Wpn-Cannon-Accuracy01",
	"R-Struc-RprFac-Upgrade03", "R-Comp-SynapticLink", "R-Vehicle-Engine02",
	"R-Struc-Factory-Upgrade03", "R-Struc-Factory-Cyborg", "R-Cyborg-Wpn-MG",
	"R-Cyborg-Metals01", "R-Cyborg-Metals02", "R-Cyborg-Metals03", "R-Cyborg-Wpn-Cannon",
	"R-Cyborg-Wpn-Rocket", "R-Cyborg-Legs01"
];
